// examples/react/assets/js/Counter.tsx
import { useState, useMemo } from 'react'

export default function Counter() {
  const [count, setCount] = useState(0)
  const doubled = useMemo(() => count * 2, [count])

  return (
    <div>
      <button
        type="button"
        className="rounded-full bg-sky-600 px-5 py-2.5 font-semibold text-white shadow-md shadow-sky-600/25 transition hover:-translate-y-0.5 hover:bg-sky-700"
        onClick={() => setCount((v) => v + 1)}
      >
        Count is {count}
      </button>
      <p className="mt-3 text-sm text-slate-500">Doubled: {doubled}</p>
    </div>
  )
}

// examples/vue/assets/js/Counter.vue
<script setup lang="ts">
import { computed, ref } from 'vue'

const count = ref(0)
const doubled = computed(() => count.value * 2)
</script>

<template>
  <div>
    <button
      type="button"
      class="rounded-full bg-indigo-600 px-5 py-2.5 font-semibold text-white shadow-md shadow-indigo-600/25 transition hover:-translate-y-0.5 hover:bg-indigo-700"
      @click="count++"
    >
      Count is {{ count }}
    </button>
    <p class="mt-3 text-sm text-slate-500">Doubled: {{ doubled }}</p>
  </div>
</template>
